### ISSUE TITLE
Device list shows only blue tooth devices

### ISSUE THREAD

**Issue by braillescreen** [cartertemm/teamtalk-spotify-bot#1]
When I run the bot and try to get a device list, it only shows my echo devices as my possible output devices. My output below.

> C:\Users\Owner\git\teamtalk-spotify-bot>python spotify_bot.py
1: Patrick's 3rd Echo Dot: 50%
2: Patrick's Echo: 28%
3: Patrick's 4th Echo Dot: 50%
4: Everywhere: 39%
5: Patrick's 2nd Echo Dot: 33%
Select a device:

**Comment by cartertemm** [comment]
I'm assuming you want to output from the desktop app. Assuming it is open, try pressing play and rerunning the bot.
